/*
# Create school finance system tables

1. New Tables
- `alunos`: student registry with name, registration, class, guardian contact, status and balance.
- `pagamentos`: student payments with amount, reference month, payment method, status and receipt code.
- `pedidos_saida`: expense requests with category, supplier, amount, due date, status and requester.
- `auditoria`: append-only operational log for visible activity history.
- `funcionarios`: staff registry for the administrative module.
- `salarios`: monthly payroll records linked to staff.

2. Security
- Row Level Security is enabled on every table.
- This is a single-school installation without sign-in in the current interface, so anon and authenticated roles receive CRUD access for the shared school workspace.
- Audit records are insertable and readable for the workspace but are not exposed through destructive UI actions.

3. Important notes
- All identifiers are generated by PostgreSQL.
- Monetary values use numeric(12,2) to avoid floating point storage issues.
- Status fields use text with safe defaults so the interface can evolve without destructive schema changes.
*/

CREATE TABLE IF NOT EXISTS alunos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  matricula text NOT NULL UNIQUE,
  turma text NOT NULL,
  responsavel text,
  telefone text,
  email text,
  mensalidade numeric(12,2) NOT NULL DEFAULT 0,
  saldo numeric(12,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Ativo',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pagamentos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  aluno_id uuid NOT NULL REFERENCES alunos(id) ON DELETE RESTRICT,
  valor numeric(12,2) NOT NULL,
  competencia text NOT NULL,
  metodo text NOT NULL DEFAULT 'Transferência',
  status text NOT NULL DEFAULT 'Confirmado',
  recibo text NOT NULL UNIQUE,
  observacao text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pedidos_saida (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  descricao text NOT NULL,
  categoria text NOT NULL,
  fornecedor text,
  valor numeric(12,2) NOT NULL,
  vencimento date,
  status text NOT NULL DEFAULT 'Pendente',
  solicitado_por text NOT NULL DEFAULT 'Secretaria',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auditoria (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  acao text NOT NULL,
  entidade text NOT NULL,
  descricao text NOT NULL,
  responsavel text NOT NULL DEFAULT 'Operador atual',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS funcionarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  cargo text NOT NULL,
  departamento text NOT NULL,
  salario numeric(12,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Ativo',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS salarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  funcionario_id uuid NOT NULL REFERENCES funcionarios(id) ON DELETE RESTRICT,
  competencia text NOT NULL,
  valor numeric(12,2) NOT NULL,
  status text NOT NULL DEFAULT 'Pendente',
  pago_em date,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (funcionario_id, competencia)
);

CREATE INDEX IF NOT EXISTS pagamentos_aluno_id_idx ON pagamentos(aluno_id);
CREATE INDEX IF NOT EXISTS pagamentos_created_at_idx ON pagamentos(created_at DESC);
CREATE INDEX IF NOT EXISTS pedidos_saida_created_at_idx ON pedidos_saida(created_at DESC);
CREATE INDEX IF NOT EXISTS auditoria_created_at_idx ON auditoria(created_at DESC);

ALTER TABLE alunos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos_saida ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE funcionarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE salarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "workspace_select_alunos" ON alunos;
CREATE POLICY "workspace_select_alunos" ON alunos FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace_insert_alunos" ON alunos;
CREATE POLICY "workspace_insert_alunos" ON alunos FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_update_alunos" ON alunos;
CREATE POLICY "workspace_update_alunos" ON alunos FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_delete_alunos" ON alunos;
CREATE POLICY "workspace_delete_alunos" ON alunos FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "workspace_select_pagamentos" ON pagamentos;
CREATE POLICY "workspace_select_pagamentos" ON pagamentos FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace_insert_pagamentos" ON pagamentos;
CREATE POLICY "workspace_insert_pagamentos" ON pagamentos FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_update_pagamentos" ON pagamentos;
CREATE POLICY "workspace_update_pagamentos" ON pagamentos FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_delete_pagamentos" ON pagamentos;
CREATE POLICY "workspace_delete_pagamentos" ON pagamentos FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "workspace_select_pedidos_saida" ON pedidos_saida;
CREATE POLICY "workspace_select_pedidos_saida" ON pedidos_saida FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace_insert_pedidos_saida" ON pedidos_saida;
CREATE POLICY "workspace_insert_pedidos_saida" ON pedidos_saida FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_update_pedidos_saida" ON pedidos_saida;
CREATE POLICY "workspace_update_pedidos_saida" ON pedidos_saida FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_delete_pedidos_saida" ON pedidos_saida;
CREATE POLICY "workspace_delete_pedidos_saida" ON pedidos_saida FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "workspace_select_auditoria" ON auditoria;
CREATE POLICY "workspace_select_auditoria" ON auditoria FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace_insert_auditoria" ON auditoria;
CREATE POLICY "workspace_insert_auditoria" ON auditoria FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_update_auditoria" ON auditoria;
CREATE POLICY "workspace_update_auditoria" ON auditoria FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_delete_auditoria" ON auditoria;
CREATE POLICY "workspace_delete_auditoria" ON auditoria FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "workspace_select_funcionarios" ON funcionarios;
CREATE POLICY "workspace_select_funcionarios" ON funcionarios FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace_insert_funcionarios" ON funcionarios;
CREATE POLICY "workspace_insert_funcionarios" ON funcionarios FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_update_funcionarios" ON funcionarios;
CREATE POLICY "workspace_update_funcionarios" ON funcionarios FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_delete_funcionarios" ON funcionarios;
CREATE POLICY "workspace_delete_funcionarios" ON funcionarios FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "workspace_select_salarios" ON salarios;
CREATE POLICY "workspace_select_salarios" ON salarios FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace_insert_salarios" ON salarios;
CREATE POLICY "workspace_insert_salarios" ON salarios FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_update_salarios" ON salarios;
CREATE POLICY "workspace_update_salarios" ON salarios FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_delete_salarios" ON salarios;
CREATE POLICY "workspace_delete_salarios" ON salarios FOR DELETE TO anon, authenticated USING (true);