/*
# Update schema for Estrela Dourada De Belas

1. Changes to `alunos`
- Add `classe` (text) — education level (e.g., 1ª Classe, 2ª Classe).
- Add `turno` (text) — morning/afternoon/evening shift.
- Add `data_entrada` (date) — when the student entered the school system.
- Remove fictitious/demo rows so the school starts with real data only.

2. Changes to `pagamentos`
- Add `tipo` (text) — payment type: Propina, Uniforme, Cartão, Folha de Provas.
- Add `data_pagamento` (date) — actual date the payment was made.
- Add `utilizador` (text) — user who registered the payment.
- Keep existing columns (aluno_id, valor, competencia, metodo, status, recibo).

3. Changes to `pedidos_saida`
- Add `tipo` (text) — Fundos or Materiais.
- Add `decisao_por` (text) — admin who approved/rejected.
- Add `decisao_em` (timestamptz) — when the decision was made.

4. New table: `notificacoes`
- Stores notifications generated by fund/material requests.
- Linked to `pedidos_saida` via foreign key.
- Has `lida` (boolean) for read state.

5. Changes to `auditoria`
- Add `valor_anterior` (jsonb) — state before the change.
- Add `valor_novo` (jsonb) — state after the change.
- Add `entidade_id` (uuid) — ID of the affected record (nullable, no FK since it can reference different tables).

6. Data cleanup
- DELETE all rows from alunos, pagamentos, pedidos_saida, auditoria, funcionarios, salarios to remove fictitious data.

7. Security
- RLS policies updated for new tables (notificacoes).
- All existing policies remain valid.
*/

-- Add new columns to alunos
ALTER TABLE alunos ADD COLUMN IF NOT EXISTS classe text NOT NULL DEFAULT '1ª Classe';
ALTER TABLE alunos ADD COLUMN IF NOT EXISTS turno text NOT NULL DEFAULT 'Manhã';
ALTER TABLE alunos ADD COLUMN IF NOT EXISTS data_entrada date DEFAULT CURRENT_DATE;

-- Add new columns to pagamentos
ALTER TABLE pagamentos ADD COLUMN IF NOT EXISTS tipo text NOT NULL DEFAULT 'Propina';
ALTER TABLE pagamentos ADD COLUMN IF NOT EXISTS data_pagamento date DEFAULT CURRENT_DATE;
ALTER TABLE pagamentos ADD COLUMN IF NOT EXISTS utilizador text NOT NULL DEFAULT 'Operador';

-- Add new columns to pedidos_saida
ALTER TABLE pedidos_saida ADD COLUMN IF NOT EXISTS tipo text NOT NULL DEFAULT 'Fundos';
ALTER TABLE pedidos_saida ADD COLUMN IF NOT EXISTS decisao_por text;
ALTER TABLE pedidos_saida ADD COLUMN IF NOT EXISTS decisao_em timestamptz;

-- Add new columns to auditoria
ALTER TABLE auditoria ADD COLUMN IF NOT EXISTS valor_anterior jsonb;
ALTER TABLE auditoria ADD COLUMN IF NOT EXISTS valor_novo jsonb;
ALTER TABLE auditoria ADD COLUMN IF NOT EXISTS entidade_id uuid;

-- Create notificacoes table
CREATE TABLE IF NOT EXISTS notificacoes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id uuid REFERENCES pedidos_saida(id) ON DELETE CASCADE,
  titulo text NOT NULL,
  descricao text NOT NULL,
  lida boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notificacoes_lida_idx ON notificacoes(lida);
CREATE INDEX IF NOT EXISTS notificacoes_created_at_idx ON notificacoes(created_at DESC);

ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "workspace_select_notificacoes" ON notificacoes;
CREATE POLICY "workspace_select_notificacoes" ON notificacoes FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace_insert_notificacoes" ON notificacoes;
CREATE POLICY "workspace_insert_notificacoes" ON notificacoes FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_update_notificacoes" ON notificacoes;
CREATE POLICY "workspace_update_notificacoes" ON notificacoes FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace_delete_notificacoes" ON notificacoes;
CREATE POLICY "workspace_delete_notificacoes" ON notificacoes FOR DELETE TO anon, authenticated USING (true);

-- Clear all fictitious data
DELETE FROM salarios;
DELETE FROM funcionarios;
DELETE FROM auditoria;
DELETE FROM notificacoes;
DELETE FROM pedidos_saida;
DELETE FROM pagamentos;
DELETE FROM alunos;